### ISSUE TITLE
python: can't open file 'C:\\Users\\Username\\docx2md\\convert.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by HoratioVonBecker** [YianniR/docx2md#2]
The listed instructions were oddly unclear - I needed to install Python and Git, but installing the supplementary Python packages was included in both the launch instructions and the prerequisites.
The launch instructions implied they could be done from one program - I'm guessing Git Bash? - but did not specify which terminal to use. I installed the Python dependencies through Windows Command Prompt, and cloned the file using Git Bash. Then I did `cd docx2md` as instructed, followed by `python convert.py`, first from Git Bash and then from Windows Command Prompt, because both times they threw the same error message:
`python: can't open file 'C:\\Users\\Username\\docx2md\\convert.py': [Errno 2] No such file or directory`

**Comment by YianniR** [comment]
Are you sure you are in the right directory?

Please make sure you are in the docx2md folder, and type

`ls -la`

to view its contents

**Comment by HoratioVonBecker** [comment]
`
Mum@DESKTOP-5813GHA MINGW32 ~/docx2md (main)
$ ls -la
total 165
drwxr-xr-x 1 Mum 197121      0 Apr 18 20:46 ./
drwxr-xr-x 1 Mum 197121      0 Apr 18 20:46 ../
drwxr-xr-x 1 Mum 197121      0 Apr 18 20:46 .git/
-rw-r--r-- 1 Mum 197121    347 Apr 18 20:46 .gitignore
-rw-r--r-- 1 Mum 197121   1090 Apr 18 20:46 LICENCE
-rw-r--r-- 1 Mum 197121   2308 Apr 18 20:46 README.md
-rw-r--r-- 1 Mum 197121   3558 Apr 18 20:46 docx2md.py
-rw-r--r-- 1 Mum 197121 115727 Apr 18 20:46 logo.png
-rw-r--r-- 1 Mum 197121  13917 Apr 18 20:46 screenshot.png`

**Comment by YianniR** [comment]
Thanks. The file you need to run is docx2md.py. The readme needs to be updated, thanks for noticing that I will update the instructions.

**Comment by HoratioVonBecker** [comment]
Thank you!
